// Mock MIDI device database for the semantic CC picker.
// Elektron Analog Four MKII data sourced from midi.guide (CC parameters only).
// Other devices use representative parameter sets.
// In production this is replaced with the full midi.guide dataset.

export type MidiParameter = { id: string; name: string; cc: number; category: string }
export type MidiDevice = { id: string; name: string; categories: string[]; parameters: MidiParameter[] }

export const MIDI_DEVICES: MidiDevice[] = [
  {
    id: 'elektron-analog-four-mkii',
    name: 'Elektron Analog Four MKII',
    categories: ['Performance', 'OSC', 'Filters', 'Amp', 'Envelopes', 'LFOs'],
    parameters: [
      // Performance
      { id: 'perf-a', name: 'Performance A', cc: 3, category: 'Performance' },
      { id: 'perf-b', name: 'Performance B', cc: 4, category: 'Performance' },
      { id: 'perf-c', name: 'Performance C', cc: 8, category: 'Performance' },
      { id: 'perf-d', name: 'Performance D', cc: 9, category: 'Performance' },
      { id: 'perf-e', name: 'Performance E', cc: 11, category: 'Performance' },
      { id: 'perf-f', name: 'Performance F', cc: 64, category: 'Performance' },
      { id: 'perf-g', name: 'Performance G', cc: 65, category: 'Performance' },
      { id: 'perf-h', name: 'Performance H', cc: 66, category: 'Performance' },
      { id: 'perf-i', name: 'Performance I', cc: 67, category: 'Performance' },
      { id: 'perf-j', name: 'Performance J', cc: 68, category: 'Performance' },
      // OSC
      { id: 'osc1-level', name: 'OSC1 Level', cc: 69, category: 'OSC' },
      { id: 'osc1-waveform', name: 'OSC1 Waveform', cc: 70, category: 'OSC' },
      { id: 'osc1-sub', name: 'OSC1 Sub Oscillator', cc: 71, category: 'OSC' },
      { id: 'osc1-pw', name: 'OSC1 Pulsewidth', cc: 72, category: 'OSC' },
      { id: 'osc1-pwm-speed', name: 'OSC1 PWM Speed', cc: 73, category: 'OSC' },
      { id: 'osc1-pwm-depth', name: 'OSC1 PWM Depth', cc: 74, category: 'OSC' },
      { id: 'osc2-level', name: 'OSC2 Level', cc: 78, category: 'OSC' },
      { id: 'osc2-waveform', name: 'OSC2 Waveform', cc: 79, category: 'OSC' },
      { id: 'osc2-sub', name: 'OSC2 Sub Oscillator', cc: 80, category: 'OSC' },
      { id: 'osc2-pw', name: 'OSC2 Pulsewidth', cc: 81, category: 'OSC' },
      { id: 'osc2-pwm-speed', name: 'OSC2 PWM Speed', cc: 82, category: 'OSC' },
      { id: 'osc2-pwm-depth', name: 'OSC2 PWM Depth', cc: 83, category: 'OSC' },
      { id: 'osc-sync-amount', name: 'OSC Sync Amount', cc: 84, category: 'OSC' },
      { id: 'osc-bend', name: 'OSC Bend Amount', cc: 85, category: 'OSC' },
      { id: 'osc-slide', name: 'OSC Slide Time', cc: 5, category: 'OSC' },
      { id: 'osc-vibrato-speed', name: 'OSC Vibrato Speed', cc: 87, category: 'OSC' },
      { id: 'osc-vibrato-depth', name: 'OSC Vibrato Depth', cc: 88, category: 'OSC' },
      { id: 'noise-sh', name: 'Noise S&H', cc: 75, category: 'OSC' },
      { id: 'noise-fade', name: 'Noise Fade', cc: 76, category: 'OSC' },
      { id: 'noise-level', name: 'Noise Level', cc: 77, category: 'OSC' },
      // Filters
      { id: 'f1-freq', name: 'Filter 1 Frequency', cc: 18, category: 'Filters' },
      { id: 'f1-res', name: 'Filter 1 Resonance', cc: 89, category: 'Filters' },
      { id: 'f1-drive', name: 'Filter 1 Overdrive', cc: 86, category: 'Filters' },
      { id: 'f1-env-depth', name: 'Filter 1 Envelope Depth', cc: 102, category: 'Filters' },
      { id: 'f2-freq', name: 'Filter 2 Frequency', cc: 19, category: 'Filters' },
      { id: 'f2-res', name: 'Filter 2 Resonance', cc: 90, category: 'Filters' },
      { id: 'f2-env-depth', name: 'Filter 2 Envelope Depth', cc: 103, category: 'Filters' },
      // Amp
      { id: 'amp-chorus', name: 'Amp Chorus Send', cc: 91, category: 'Amp' },
      { id: 'amp-delay', name: 'Amp Delay Send', cc: 92, category: 'Amp' },
      { id: 'amp-reverb', name: 'Amp Reverb Send', cc: 93, category: 'Amp' },
      { id: 'amp-pan', name: 'Amp Pan', cc: 10, category: 'Amp' },
      { id: 'amp-volume', name: 'Amp Volume', cc: 7, category: 'Amp' },
      // Envelopes
      { id: 'amp-env-attack', name: 'Amp Env Attack', cc: 104, category: 'Envelopes' },
      { id: 'amp-env-decay', name: 'Amp Env Decay', cc: 105, category: 'Envelopes' },
      { id: 'amp-env-sustain', name: 'Amp Env Sustain', cc: 106, category: 'Envelopes' },
      { id: 'amp-env-release', name: 'Amp Env Release', cc: 107, category: 'Envelopes' },
      { id: 'flt-env-attack', name: 'Filter Env Attack', cc: 108, category: 'Envelopes' },
      { id: 'flt-env-decay', name: 'Filter Env Decay', cc: 109, category: 'Envelopes' },
      { id: 'flt-env-sustain', name: 'Filter Env Sustain', cc: 110, category: 'Envelopes' },
      { id: 'flt-env-release', name: 'Filter Env Release', cc: 111, category: 'Envelopes' },
      { id: 'aux-env-attack', name: 'AUX Env Attack', cc: 112, category: 'Envelopes' },
      { id: 'aux-env-decay', name: 'AUX Env Decay', cc: 113, category: 'Envelopes' },
      { id: 'aux-env-sustain', name: 'AUX Env Sustain', cc: 114, category: 'Envelopes' },
      { id: 'aux-env-release', name: 'AUX Env Release', cc: 115, category: 'Envelopes' },
      // LFOs
      { id: 'lfo1-speed', name: 'LFO1 Speed', cc: 116, category: 'LFOs' },
      { id: 'lfo1-multiplier', name: 'LFO1 Multiplier', cc: 117, category: 'LFOs' },
      { id: 'lfo1-depth-a', name: 'LFO1 Depth A', cc: 24, category: 'LFOs' },
      { id: 'lfo1-depth-b', name: 'LFO1 Depth B', cc: 25, category: 'LFOs' },
      { id: 'lfo2-speed', name: 'LFO2 Speed', cc: 118, category: 'LFOs' },
      { id: 'lfo2-multiplier', name: 'LFO2 Multiplier', cc: 119, category: 'LFOs' },
      { id: 'lfo2-depth-a', name: 'LFO2 Depth A', cc: 26, category: 'LFOs' },
      { id: 'lfo2-depth-b', name: 'LFO2 Depth B', cc: 27, category: 'LFOs' },
    ],
  },
  {
    id: 'elektron-analog-rytm',
    name: 'Elektron Analog Rytm',
    categories: ['Performance', 'OSC', 'Filters', 'Amp', 'Envelopes', 'LFOs'],
    parameters: [
      { id: 'perf-a', name: 'Performance A', cc: 3, category: 'Performance' },
      { id: 'perf-b', name: 'Performance B', cc: 4, category: 'Performance' },
      { id: 'perf-c', name: 'Performance C', cc: 8, category: 'Performance' },
      { id: 'osc-level', name: 'OSC Level', cc: 69, category: 'OSC' },
      { id: 'osc-waveform', name: 'OSC Waveform', cc: 70, category: 'OSC' },
      { id: 'osc-pw', name: 'OSC Pulsewidth', cc: 72, category: 'OSC' },
      { id: 'osc-slide', name: 'OSC Slide Time', cc: 5, category: 'OSC' },
      { id: 'f1-freq', name: 'Filter Frequency', cc: 18, category: 'Filters' },
      { id: 'f1-res', name: 'Filter Resonance', cc: 89, category: 'Filters' },
      { id: 'f1-drive', name: 'Filter Overdrive', cc: 86, category: 'Filters' },
      { id: 'f1-env-depth', name: 'Filter Envelope Depth', cc: 102, category: 'Filters' },
      { id: 'amp-chorus', name: 'Amp Chorus Send', cc: 91, category: 'Amp' },
      { id: 'amp-delay', name: 'Amp Delay Send', cc: 92, category: 'Amp' },
      { id: 'amp-reverb', name: 'Amp Reverb Send', cc: 93, category: 'Amp' },
      { id: 'amp-pan', name: 'Amp Pan', cc: 10, category: 'Amp' },
      { id: 'amp-volume', name: 'Amp Volume', cc: 7, category: 'Amp' },
      { id: 'amp-env-attack', name: 'Amp Env Attack', cc: 104, category: 'Envelopes' },
      { id: 'amp-env-decay', name: 'Amp Env Decay', cc: 105, category: 'Envelopes' },
      { id: 'amp-env-sustain', name: 'Amp Env Sustain', cc: 106, category: 'Envelopes' },
      { id: 'amp-env-release', name: 'Amp Env Release', cc: 107, category: 'Envelopes' },
      { id: 'flt-env-attack', name: 'Filter Env Attack', cc: 108, category: 'Envelopes' },
      { id: 'flt-env-decay', name: 'Filter Env Decay', cc: 109, category: 'Envelopes' },
      { id: 'flt-env-sustain', name: 'Filter Env Sustain', cc: 110, category: 'Envelopes' },
      { id: 'flt-env-release', name: 'Filter Env Release', cc: 111, category: 'Envelopes' },
      { id: 'lfo1-speed', name: 'LFO1 Speed', cc: 116, category: 'LFOs' },
      { id: 'lfo1-multiplier', name: 'LFO1 Multiplier', cc: 117, category: 'LFOs' },
      { id: 'lfo1-depth-a', name: 'LFO1 Depth A', cc: 24, category: 'LFOs' },
      { id: 'lfo2-speed', name: 'LFO2 Speed', cc: 118, category: 'LFOs' },
      { id: 'lfo2-multiplier', name: 'LFO2 Multiplier', cc: 119, category: 'LFOs' },
      { id: 'lfo2-depth-a', name: 'LFO2 Depth A', cc: 26, category: 'LFOs' },
    ],
  },
  {
    id: 'moog-matriarch',
    name: 'Moog Matriarch',
    categories: ['Performance', 'OSC', 'Filters', 'Amp', 'Envelopes', 'LFOs'],
    parameters: [
      { id: 'perf-a', name: 'Performance A', cc: 3, category: 'Performance' },
      { id: 'perf-b', name: 'Performance B', cc: 4, category: 'Performance' },
      { id: 'perf-c', name: 'Performance C', cc: 8, category: 'Performance' },
      { id: 'osc-level', name: 'OSC Level', cc: 69, category: 'OSC' },
      { id: 'osc-waveform', name: 'OSC Waveform', cc: 70, category: 'OSC' },
      { id: 'osc-pw', name: 'OSC Pulsewidth', cc: 72, category: 'OSC' },
      { id: 'osc-slide', name: 'OSC Slide Time', cc: 5, category: 'OSC' },
      { id: 'f1-freq', name: 'Filter Frequency', cc: 18, category: 'Filters' },
      { id: 'f1-res', name: 'Filter Resonance', cc: 89, category: 'Filters' },
      { id: 'f1-drive', name: 'Filter Overdrive', cc: 86, category: 'Filters' },
      { id: 'f1-env-depth', name: 'Filter Envelope Depth', cc: 102, category: 'Filters' },
      { id: 'amp-chorus', name: 'Amp Chorus Send', cc: 91, category: 'Amp' },
      { id: 'amp-delay', name: 'Amp Delay Send', cc: 92, category: 'Amp' },
      { id: 'amp-reverb', name: 'Amp Reverb Send', cc: 93, category: 'Amp' },
      { id: 'amp-pan', name: 'Amp Pan', cc: 10, category: 'Amp' },
      { id: 'amp-volume', name: 'Amp Volume', cc: 7, category: 'Amp' },
      { id: 'amp-env-attack', name: 'Amp Env Attack', cc: 104, category: 'Envelopes' },
      { id: 'amp-env-decay', name: 'Amp Env Decay', cc: 105, category: 'Envelopes' },
      { id: 'amp-env-sustain', name: 'Amp Env Sustain', cc: 106, category: 'Envelopes' },
      { id: 'amp-env-release', name: 'Amp Env Release', cc: 107, category: 'Envelopes' },
      { id: 'flt-env-attack', name: 'Filter Env Attack', cc: 108, category: 'Envelopes' },
      { id: 'flt-env-decay', name: 'Filter Env Decay', cc: 109, category: 'Envelopes' },
      { id: 'flt-env-sustain', name: 'Filter Env Sustain', cc: 110, category: 'Envelopes' },
      { id: 'flt-env-release', name: 'Filter Env Release', cc: 111, category: 'Envelopes' },
      { id: 'lfo1-speed', name: 'LFO1 Speed', cc: 116, category: 'LFOs' },
      { id: 'lfo1-multiplier', name: 'LFO1 Multiplier', cc: 117, category: 'LFOs' },
      { id: 'lfo1-depth-a', name: 'LFO1 Depth A', cc: 24, category: 'LFOs' },
      { id: 'lfo2-speed', name: 'LFO2 Speed', cc: 118, category: 'LFOs' },
      { id: 'lfo2-multiplier', name: 'LFO2 Multiplier', cc: 119, category: 'LFOs' },
      { id: 'lfo2-depth-a', name: 'LFO2 Depth A', cc: 26, category: 'LFOs' },
    ],
  },
  {
    id: 'arturia-microfreak',
    name: 'Arturia MicroFreak',
    categories: ['Performance', 'OSC', 'Filters', 'Amp', 'Envelopes', 'LFOs'],
    parameters: [
      { id: 'perf-a', name: 'Performance A', cc: 3, category: 'Performance' },
      { id: 'perf-b', name: 'Performance B', cc: 4, category: 'Performance' },
      { id: 'perf-c', name: 'Performance C', cc: 8, category: 'Performance' },
      { id: 'osc-level', name: 'OSC Level', cc: 69, category: 'OSC' },
      { id: 'osc-waveform', name: 'OSC Waveform', cc: 70, category: 'OSC' },
      { id: 'osc-pw', name: 'OSC Pulsewidth', cc: 72, category: 'OSC' },
      { id: 'osc-slide', name: 'OSC Slide Time', cc: 5, category: 'OSC' },
      { id: 'f1-freq', name: 'Filter Frequency', cc: 18, category: 'Filters' },
      { id: 'f1-res', name: 'Filter Resonance', cc: 89, category: 'Filters' },
      { id: 'f1-drive', name: 'Filter Overdrive', cc: 86, category: 'Filters' },
      { id: 'f1-env-depth', name: 'Filter Envelope Depth', cc: 102, category: 'Filters' },
      { id: 'amp-chorus', name: 'Amp Chorus Send', cc: 91, category: 'Amp' },
      { id: 'amp-delay', name: 'Amp Delay Send', cc: 92, category: 'Amp' },
      { id: 'amp-reverb', name: 'Amp Reverb Send', cc: 93, category: 'Amp' },
      { id: 'amp-pan', name: 'Amp Pan', cc: 10, category: 'Amp' },
      { id: 'amp-volume', name: 'Amp Volume', cc: 7, category: 'Amp' },
      { id: 'amp-env-attack', name: 'Amp Env Attack', cc: 104, category: 'Envelopes' },
      { id: 'amp-env-decay', name: 'Amp Env Decay', cc: 105, category: 'Envelopes' },
      { id: 'amp-env-sustain', name: 'Amp Env Sustain', cc: 106, category: 'Envelopes' },
      { id: 'amp-env-release', name: 'Amp Env Release', cc: 107, category: 'Envelopes' },
      { id: 'flt-env-attack', name: 'Filter Env Attack', cc: 108, category: 'Envelopes' },
      { id: 'flt-env-decay', name: 'Filter Env Decay', cc: 109, category: 'Envelopes' },
      { id: 'flt-env-sustain', name: 'Filter Env Sustain', cc: 110, category: 'Envelopes' },
      { id: 'flt-env-release', name: 'Filter Env Release', cc: 111, category: 'Envelopes' },
      { id: 'lfo1-speed', name: 'LFO1 Speed', cc: 116, category: 'LFOs' },
      { id: 'lfo1-multiplier', name: 'LFO1 Multiplier', cc: 117, category: 'LFOs' },
      { id: 'lfo1-depth-a', name: 'LFO1 Depth A', cc: 24, category: 'LFOs' },
      { id: 'lfo2-speed', name: 'LFO2 Speed', cc: 118, category: 'LFOs' },
      { id: 'lfo2-multiplier', name: 'LFO2 Multiplier', cc: 119, category: 'LFOs' },
      { id: 'lfo2-depth-a', name: 'LFO2 Depth A', cc: 26, category: 'LFOs' },
    ],
  },
  {
    id: 'korg-minilogue',
    name: 'Korg Minilogue',
    categories: ['Performance', 'OSC', 'Filters', 'Amp', 'Envelopes', 'LFOs'],
    parameters: [
      { id: 'perf-a', name: 'Performance A', cc: 3, category: 'Performance' },
      { id: 'perf-b', name: 'Performance B', cc: 4, category: 'Performance' },
      { id: 'perf-c', name: 'Performance C', cc: 8, category: 'Performance' },
      { id: 'osc-level', name: 'OSC Level', cc: 69, category: 'OSC' },
      { id: 'osc-waveform', name: 'OSC Waveform', cc: 70, category: 'OSC' },
      { id: 'osc-pw', name: 'OSC Pulsewidth', cc: 72, category: 'OSC' },
      { id: 'osc-slide', name: 'OSC Slide Time', cc: 5, category: 'OSC' },
      { id: 'f1-freq', name: 'Filter Frequency', cc: 18, category: 'Filters' },
      { id: 'f1-res', name: 'Filter Resonance', cc: 89, category: 'Filters' },
      { id: 'f1-drive', name: 'Filter Overdrive', cc: 86, category: 'Filters' },
      { id: 'f1-env-depth', name: 'Filter Envelope Depth', cc: 102, category: 'Filters' },
      { id: 'amp-chorus', name: 'Amp Chorus Send', cc: 91, category: 'Amp' },
      { id: 'amp-delay', name: 'Amp Delay Send', cc: 92, category: 'Amp' },
      { id: 'amp-reverb', name: 'Amp Reverb Send', cc: 93, category: 'Amp' },
      { id: 'amp-pan', name: 'Amp Pan', cc: 10, category: 'Amp' },
      { id: 'amp-volume', name: 'Amp Volume', cc: 7, category: 'Amp' },
      { id: 'amp-env-attack', name: 'Amp Env Attack', cc: 104, category: 'Envelopes' },
      { id: 'amp-env-decay', name: 'Amp Env Decay', cc: 105, category: 'Envelopes' },
      { id: 'amp-env-sustain', name: 'Amp Env Sustain', cc: 106, category: 'Envelopes' },
      { id: 'amp-env-release', name: 'Amp Env Release', cc: 107, category: 'Envelopes' },
      { id: 'flt-env-attack', name: 'Filter Env Attack', cc: 108, category: 'Envelopes' },
      { id: 'flt-env-decay', name: 'Filter Env Decay', cc: 109, category: 'Envelopes' },
      { id: 'flt-env-sustain', name: 'Filter Env Sustain', cc: 110, category: 'Envelopes' },
      { id: 'flt-env-release', name: 'Filter Env Release', cc: 111, category: 'Envelopes' },
      { id: 'lfo1-speed', name: 'LFO1 Speed', cc: 116, category: 'LFOs' },
      { id: 'lfo1-multiplier', name: 'LFO1 Multiplier', cc: 117, category: 'LFOs' },
      { id: 'lfo1-depth-a', name: 'LFO1 Depth A', cc: 24, category: 'LFOs' },
      { id: 'lfo2-speed', name: 'LFO2 Speed', cc: 118, category: 'LFOs' },
      { id: 'lfo2-multiplier', name: 'LFO2 Multiplier', cc: 119, category: 'LFOs' },
      { id: 'lfo2-depth-a', name: 'LFO2 Depth A', cc: 26, category: 'LFOs' },
    ],
  },
  {
    id: 'novation-bass-station-2',
    name: 'Novation Bass Station II',
    categories: ['Performance', 'OSC', 'Filters', 'Amp', 'Envelopes', 'LFOs'],
    parameters: [
      { id: 'perf-a', name: 'Performance A', cc: 3, category: 'Performance' },
      { id: 'perf-b', name: 'Performance B', cc: 4, category: 'Performance' },
      { id: 'perf-c', name: 'Performance C', cc: 8, category: 'Performance' },
      { id: 'osc-level', name: 'OSC Level', cc: 69, category: 'OSC' },
      { id: 'osc-waveform', name: 'OSC Waveform', cc: 70, category: 'OSC' },
      { id: 'osc-pw', name: 'OSC Pulsewidth', cc: 72, category: 'OSC' },
      { id: 'osc-slide', name: 'OSC Slide Time', cc: 5, category: 'OSC' },
      { id: 'f1-freq', name: 'Filter Frequency', cc: 18, category: 'Filters' },
      { id: 'f1-res', name: 'Filter Resonance', cc: 89, category: 'Filters' },
      { id: 'f1-drive', name: 'Filter Overdrive', cc: 86, category: 'Filters' },
      { id: 'f1-env-depth', name: 'Filter Envelope Depth', cc: 102, category: 'Filters' },
      { id: 'amp-chorus', name: 'Amp Chorus Send', cc: 91, category: 'Amp' },
      { id: 'amp-delay', name: 'Amp Delay Send', cc: 92, category: 'Amp' },
      { id: 'amp-reverb', name: 'Amp Reverb Send', cc: 93, category: 'Amp' },
      { id: 'amp-pan', name: 'Amp Pan', cc: 10, category: 'Amp' },
      { id: 'amp-volume', name: 'Amp Volume', cc: 7, category: 'Amp' },
      { id: 'amp-env-attack', name: 'Amp Env Attack', cc: 104, category: 'Envelopes' },
      { id: 'amp-env-decay', name: 'Amp Env Decay', cc: 105, category: 'Envelopes' },
      { id: 'amp-env-sustain', name: 'Amp Env Sustain', cc: 106, category: 'Envelopes' },
      { id: 'amp-env-release', name: 'Amp Env Release', cc: 107, category: 'Envelopes' },
      { id: 'flt-env-attack', name: 'Filter Env Attack', cc: 108, category: 'Envelopes' },
      { id: 'flt-env-decay', name: 'Filter Env Decay', cc: 109, category: 'Envelopes' },
      { id: 'flt-env-sustain', name: 'Filter Env Sustain', cc: 110, category: 'Envelopes' },
      { id: 'flt-env-release', name: 'Filter Env Release', cc: 111, category: 'Envelopes' },
      { id: 'lfo1-speed', name: 'LFO1 Speed', cc: 116, category: 'LFOs' },
      { id: 'lfo1-multiplier', name: 'LFO1 Multiplier', cc: 117, category: 'LFOs' },
      { id: 'lfo1-depth-a', name: 'LFO1 Depth A', cc: 24, category: 'LFOs' },
      { id: 'lfo2-speed', name: 'LFO2 Speed', cc: 118, category: 'LFOs' },
      { id: 'lfo2-multiplier', name: 'LFO2 Multiplier', cc: 119, category: 'LFOs' },
      { id: 'lfo2-depth-a', name: 'LFO2 Depth A', cc: 26, category: 'LFOs' },
    ],
  },
  {
    id: 'sequential-prophet-6',
    name: 'Sequential Prophet-6',
    categories: ['Performance', 'OSC', 'Filters', 'Amp', 'Envelopes', 'LFOs'],
    parameters: [
      { id: 'perf-a', name: 'Performance A', cc: 3, category: 'Performance' },
      { id: 'perf-b', name: 'Performance B', cc: 4, category: 'Performance' },
      { id: 'perf-c', name: 'Performance C', cc: 8, category: 'Performance' },
      { id: 'osc-level', name: 'OSC Level', cc: 69, category: 'OSC' },
      { id: 'osc-waveform', name: 'OSC Waveform', cc: 70, category: 'OSC' },
      { id: 'osc-pw', name: 'OSC Pulsewidth', cc: 72, category: 'OSC' },
      { id: 'osc-slide', name: 'OSC Slide Time', cc: 5, category: 'OSC' },
      { id: 'f1-freq', name: 'Filter Frequency', cc: 18, category: 'Filters' },
      { id: 'f1-res', name: 'Filter Resonance', cc: 89, category: 'Filters' },
      { id: 'f1-drive', name: 'Filter Overdrive', cc: 86, category: 'Filters' },
      { id: 'f1-env-depth', name: 'Filter Envelope Depth', cc: 102, category: 'Filters' },
      { id: 'amp-chorus', name: 'Amp Chorus Send', cc: 91, category: 'Amp' },
      { id: 'amp-delay', name: 'Amp Delay Send', cc: 92, category: 'Amp' },
      { id: 'amp-reverb', name: 'Amp Reverb Send', cc: 93, category: 'Amp' },
      { id: 'amp-pan', name: 'Amp Pan', cc: 10, category: 'Amp' },
      { id: 'amp-volume', name: 'Amp Volume', cc: 7, category: 'Amp' },
      { id: 'amp-env-attack', name: 'Amp Env Attack', cc: 104, category: 'Envelopes' },
      { id: 'amp-env-decay', name: 'Amp Env Decay', cc: 105, category: 'Envelopes' },
      { id: 'amp-env-sustain', name: 'Amp Env Sustain', cc: 106, category: 'Envelopes' },
      { id: 'amp-env-release', name: 'Amp Env Release', cc: 107, category: 'Envelopes' },
      { id: 'flt-env-attack', name: 'Filter Env Attack', cc: 108, category: 'Envelopes' },
      { id: 'flt-env-decay', name: 'Filter Env Decay', cc: 109, category: 'Envelopes' },
      { id: 'flt-env-sustain', name: 'Filter Env Sustain', cc: 110, category: 'Envelopes' },
      { id: 'flt-env-release', name: 'Filter Env Release', cc: 111, category: 'Envelopes' },
      { id: 'lfo1-speed', name: 'LFO1 Speed', cc: 116, category: 'LFOs' },
      { id: 'lfo1-multiplier', name: 'LFO1 Multiplier', cc: 117, category: 'LFOs' },
      { id: 'lfo1-depth-a', name: 'LFO1 Depth A', cc: 24, category: 'LFOs' },
      { id: 'lfo2-speed', name: 'LFO2 Speed', cc: 118, category: 'LFOs' },
      { id: 'lfo2-multiplier', name: 'LFO2 Multiplier', cc: 119, category: 'LFOs' },
      { id: 'lfo2-depth-a', name: 'LFO2 Depth A', cc: 26, category: 'LFOs' },
    ],
  },
]

export function findMidiDevice(deviceId?: string): MidiDevice | undefined {
  return MIDI_DEVICES.find((device) => device.id === deviceId)
}

export function findMidiParameter(deviceId?: string, paramId?: string): MidiParameter | undefined {
  return findMidiDevice(deviceId)?.parameters.find((param) => param.id === paramId)
}
